apiVersion: v1
kind: ConfigMap
metadata:
  name: loja-veloz-config
  namespace: loja-veloz
data:
  NODE_ENV: "production"
  PORT: "8000"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "loja_veloz"
  PEDIDOS_SERVICE_URL: "http://pedidos-service:3000"
  PAGAMENTOS_SERVICE_URL: "http://pagamentos-service:3001"
  ESTOQUE_SERVICE_URL: "http://estoque-service:3002"
