apiVersion: v1
kind: Secret
metadata:
  name: loja-veloz-secrets
  namespace: loja-veloz
type: Opaque
stringData:
  DB_USER: "devuser"
  DB_PASSWORD: "devpassword"
  DATABASE_URL: "postgres://devuser:devpassword@postgres-service:5432/loja_veloz"
